version: 2

sources:
  - name: silver_screen #name of the source we will reference in the models
    database: silver_screen #name of database as can be found on snowflake
    schema: public
    tables: #name of tables we're referencing in the models as can be found on snowflake
      - name: movie_catalogue
      - name: invoices
      - name: nj_001
      - name: nj_002
      - name: nj_003
models:
  - name: stg_movie_catalogue
    description: This model selects the needed columns from movie_catalogue and cleans the data to insure we have them unique and not_null where needed.
    columns:
      - name: movie_id
        tests:
          - unique
          - not_null
      - name: movie_title
        tests:
          - not_null
      - name: genre
        tests:
          - not_null
      - name: studio
        tests:
          - not_null
  - name: stg_invoices
    description: This model selects the needed columns from invoices and cleans the data to insure we have them unique and not_null where needed.
    columns:
      - name: month
        tests:
        - not_null
      - name: location_id
        tests:
          - not_null
  - name: locations_monthly_sales
    description: This model combines all the transaction data from all three different locations and aggregates the needed data
    columns:
      - name: movie_id
        tests:
          - not_null
  - name: mart_movie_monthly_performance
    description: This model joins the table with all the transactions and the table with the full movie info in order to have a full overview of the movies performance across locations
    columns:
      - name: movie_id
        tests:
          - not_null
      - name: month
        tests:
          - not_null
      - name: movie_title
        tests:
          - not_null
      - name: genre
        tests:
          - not_null
      - name: studio
        tests:
          - not_null
      - name: location
        tests:
          - not_null
      - name: rental_cost
        tests:
          - not_null
      - name: ticket_sold
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
          
          
